### ISSUE TITLE
Enable compute node timeouts?

### ISSUE THREAD

**Issue by p-1603** [ComputeCanada/puppet-magic_castle#200]
Hello,

This is a very basic question, but in many other open source HPC projects (parallelcluster, cluster in the cloud, etc), compute nodes can be set only to be created when there are jobs to run, and those that are unused for a period of time are automatically shut down and destroyed.

Does Magic Castle have this feature? The nodes on clusters I have created are static, and I cannot find anything about this in the documentation.

Thank you,

Alex

**Comment by ocaisa** [comment]
The basic issue is the risk of compromising your cloud credentials. We had a working proof-of-concept that coupled Terraform Cloud to a (private) GitHub repo with a GitHub token that had permissions to write a commit status. This setup could be used to trigger automatic scaling with the only exposed credential being the (maximally limited) GitHub token.

**Comment by p-1603** [comment]
```
instances = {
    mgmt   = { type = "b2-7", tags = ["puppet", "mgmt", "nfs"], count = 1 }
    login  = { type = "b2-7", tags = ["login", "public", "proxy"], count = 1 }
    node   = { type = "b2-7", tags = ["node"], count = 1 }
  }
```

Thank you for your quick replies. This is my `instances` setting in my `main.tf`. I see I can scale the node count up and down here as I might need, but I'm wondering how this will/can work if I have jobs running. Is there any way I could specify which nodes stay up or are terminated? Or would I simply have to wait until all jobs are complete before running `terraform apply`?

**Comment by p-1603** [comment]
I've given this a go. I also updated the `slurm.conf.tpl` in `/etc/slurm/`, but the problem still seems to persist. The extra lines remain in `slurm.conf.epp`, but are quickly removed in both `slurm.conf` and `slurm.conf.tpl`.

Is it Puppet that does this, or something else?

**Comment by cmd-ntrf** [comment]
To manage dynamically the content of /etc/slurm/node.conf when adding/removing nodes via Terraform, I implemented the generation of slurm.conf and node.conf with consul and consul-template.

When a node boots, it adds itself to a the consul cluster and consul-template regenerates the node.conf file. There is also a consul watch for slurm.conf in case slurmctld host changes dynamically.

consul-template reads the *.tpl file when it starts, and there is probably a trigger missing in puppet to let consul-template knows the template has changed.

Try restarting the `consul-template` service on the node where the files are being overwritten.

**Comment by p-1603** [comment]
That worked, great. Thank you. The `slurm.conf` now inherits from the `slurm.conf.epp`.

The suspend script works fine and the node now powers down after the timeout, and I assume on job submission the resume request should get sent and bring the node back up, but instead when I submit a job I get the following error:

```
$ sbatch test.job 
sbatch: error: Memory specification can not be satisfied
sbatch: error: Batch job submission failed: Requested node configuration is not available
```

I know the job works when the node is up, so there isn't actually a memory error, but I assume there is some Slurm setting that prevents the job being accepted when there are no nodes. Do you know what it might be?

**Comment by p-1603** [comment]
I think I've worked it out. I changed `DefMemPerNode` in `slurm.conf` from 256 to unlimited and now the submission works.

**Comment by cmd-ntrf** [comment]
This happens because the content of `node.conf` is dynamically generated by consul-template when nodes are turned on/off. Because the nodes are missing from the config file when they are shutdown, Slurm resume script is unable to identify which it nodes it should boot.

If you change `DefMemPerNode` to unlimited, the submission will work, but no node will be boot up.

To fix the issue, `node.conf` would have to be generated once instead by puppet of being generated consul-template every time a node power state changes.

**Comment by p-1603** [comment]
I see you are right. The nodes doesn't seem to boot. 

Does that mean that if I stop consul-template updating `node.conf` once the cluster is up, then it should work? I don't quite follow why `node.conf` is re-written each time the node state changes.

**Comment by p-1603** [comment]
To expand on the above a little, when use the `elastic` branches of Magic Castle and Puppet, I find the `draft.conf` is created as expected, and contains the details of the node1 that I specify in `main.tf` (I assume it should have both the `node` and `draft` tags, however node1itself is not provisioned.

**Comment by cmd-ntrf** [comment]
> It feels as if there might be multiple things I have wrong here. Would it be possible maybe to have a call to talk through this?

Sure, send me an email at: felix at calculquebec . ca

**Comment by ocaisa** [comment]
Were you talking to the OVH API to do the suspend? Destruction and creation would only work if you do it via Terraform (possible but a little tricky),  otherwise you won't have puppet.

**Comment by p-1603** [comment]
For creation and destruction I was trying to copy the way that Cluster In
The Cloud does it. The node specifications for slurm.conf are built by the
code in update_config.py, and then the API for OCI/AWS/Google is used to
create and destroy nodes on the fly:
https://github.com/clusterinthecloud/ansible/tree/6/roles/slurm/files

I was only able to get it half-working using the OVH CLI. Sadly I don't
think I understand the networks and credentials quite well enough to get
slurmctld and slurmd to recognise one another fully. Slurmd was accepting
jobs but not reporting them back.

For resume and suspend I was also using the OVH CLI. I was storing the
passwords in plain text, but I was thinking I could somehow set them as
environment variables with Puppet.

**Comment by ocaisa** [comment]
CitC uses Ansible rather than Puppet (a push rather than a pull model) so it won't work the same. For Magic Castle you need the Terraform setup to get the nodes in a state that they can talk to Puppet.

If you use the OVH api to do the node suspension then I would have thought that that would work, the node should just disappear. You would then use the OVH api to bring it back up again when needed. The big advantage to this is that you don't change/invalidate the information that Terraform has, you just change it's state. You can test your ability to remove/add a node with just the command line, if you can get it working without causing problems that way, then getting it to work directly with Slurm should be do-able.

For destruction/creation, you really have to manage this via Terraform (for example via Terraform Cloud so you have a central location you can talk to). However, MC is not currently set up to remove/add random nodes (though there has been some work on this) so this would be a bit of a journey.
